on: [push]
name: variable substitution in json

jobs:
build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/variable-substitution@v1 
    with:
        files: 'values.yaml'
    env:
        username: bob
        password: ${{ secrets.PASSWORD }}
        url: https://github.com/${{github.repository}}
